version: "3"

services:
  vote:
    build: ./vote
    image: ${REGISTRY:-aksdemobb.azurecr.io}/dockersamples/examplevotingapp_result:${BUILD_BUILDID:-latest}
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    image: ${REGISTRY:-aksdemobb.azurecr.io}/dockersamples/examplevotingapp_vote:${BUILD_BUILDID:-latest}
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.j
    image: ${REGISTRY:-aksdemobb.azurecr.io}/dockersamples/examplevotingapp_worker:${BUILD_BUILDID:-latest}
    depends_on:
      - "redis"
      - "db"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
