apiVersion: v1
kind: Service
metadata:
  labels:
    app: result-lb
  name: result-lb
  namespace: vote
spec:
  type: LoadBalancer
  ports:
  - name: "result-lb"
    port: 80
    targetPort: 80
  selector:
    type: green
    app: result
