apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-lb
  name: vote-lb
  namespace: vote
spec:
  type: LoadBalancer
  ports:
  - name: "vote-lb"
    port: 80
    targetPort: 80
  selector:
    type: green
    app-prefix: vote
  
