apiVersion: v1
kind: Service
metadata:
  labels:
    app: result-blue
  name: result-blue
  namespace: vote
spec:
  type: ClusterIP
  ports:
  - name: "result-service"
    port: 80
    targetPort: 80
  selector:
    type: blue
    app: result