apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-blue
  name: vote-blue
  namespace: vote
spec:
  type: ClusterIP
  ports:
  - name: "vote-service"
    port: 80
    targetPort: 80
  selector:
    type: blue
    app: vote
  
