apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
    build: "{{ .Values.BuildID }}"
  name: vote-{{ .Values.BuildID }}
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-{{ .Values.BuildID }}
  template:
    metadata:
      labels:
        app: vote-{{ .Values.BuildID }}
        app-prefix: vote
        build: "{{ .Values.BuildID }}"
        type: blue
    spec:
      containers:
      - image: {{.Values.Registry}}/dockersamples/examplevotingapp_vote:{{ .Values.BuildID }}
        name: vote
        ports:
        - containerPort: 80
          name: vote
